### ISSUE TITLE
Run utils_tf_test.py Failed

### ISSUE THREAD

**Issue by jinze1994** [deepmind/graph_nets#19]
```
$python utils_tf_test.py
...
======================================================================
FAIL: test_fill_edge_state_edge size 0 (__main__.GraphsCompletionTests)
test_fill_edge_state_edge size 0 (__main__.GraphsCompletionTests)
test_fill_edge_state_edge size 0(0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/absl/testing/parameterized.py", line 258, in bound_param_test
    test_method(self, *testcase_params)
  File "utils_tf_test.py", line 612, in test_fill_edge_state
    graphs_tuple.edges.get_shape().as_list())
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1381, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg=msg)
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 50.0%)
 x: array([6, 0])
 y: array([None, 0], dtype=object)

======================================================================
FAIL: test_fill_edge_state_edge size 1 (__main__.GraphsCompletionTests)
test_fill_edge_state_edge size 1 (__main__.GraphsCompletionTests)
test_fill_edge_state_edge size 1(1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/absl/testing/parameterized.py", line 258, in bound_param_test
    test_method(self, *testcase_params)
  File "utils_tf_test.py", line 612, in test_fill_edge_state
    graphs_tuple.edges.get_shape().as_list())
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1381, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg=msg)
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 50.0%)
 x: array([6, 1])
 y: array([None, 1], dtype=object)

======================================================================
FAIL: test_fill_node_state_node size 0 (__main__.GraphsCompletionTests)
test_fill_node_state_node size 0 (__main__.GraphsCompletionTests)
test_fill_node_state_node size 0(0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/absl/testing/parameterized.py", line 258, in bound_param_test
    test_method(self, *testcase_params)
  File "utils_tf_test.py", line 667, in test_fill_node_state
    graphs_tuple.nodes.get_shape().as_list())
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1381, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg=msg)
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 50.0%)
 x: array([9, 0])
 y: array([None, 0], dtype=object)

======================================================================
FAIL: test_fill_node_state_node size 1 (__main__.GraphsCompletionTests)
test_fill_node_state_node size 1 (__main__.GraphsCompletionTests)
test_fill_node_state_node size 1(1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/absl/testing/parameterized.py", line 258, in bound_param_test
    test_method(self, *testcase_params)
  File "utils_tf_test.py", line 667, in test_fill_node_state
    graphs_tuple.nodes.get_shape().as_list())
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1381, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg=msg)
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/jinze/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 50.0%)
 x: array([9, 1])
 y: array([None, 1], dtype=object)

----------------------------------------------------------------------
Ran 98 tests in 8.310s

FAILED (failures=4)
```

**Comment by alvarosg** [comment]
The test seems to be running for us. Are you running in the lastest version of TF? TensorFlow shape inference has improved lately, so running an older version could explain getting None shapes, instead of the actual shapes.

**Comment by vbapst** [comment]
More precisely, this commit:
https://github.com/tensorflow/tensorflow/commit/1d74a69443f741e69f9f52cb6bc2940b4d4ae3b7
