### ISSUE TITLE
Nodes without feature

### ISSUE THREAD

**Issue by FarshidShekari** [deepmind/graph_nets#22]
My nodes haven't feature in my problem and  I used None for that purpose but I get below error when running my code:
`AttributeError: 'NoneType' object has no attribute 'get_shape'`

when I added popery to feature I can run it.

tnx

**Comment by vbapst** [comment]
Hi Farshid,

can you provide a more complete stack trace ? Thanks.

**Comment by FarshidShekari** [comment]
Hi @vbapst 
This is my stack trace:
Traceback (most recent call last):
```
  File "C:/Users/Farshid/PycharmProjects/clique/Main2.py", line 112, in <module>
    output_ops_tr = model(input_ph, num_processing_steps_tr)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 122, in _build
    latent = self._encoder(input_op)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 56, in _build
    return self._network(inputs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\modules.py", line 366, in _build
    edges=self._edge_model(graph.edges),
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 715, in _build
    return self._build_function(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\modules.py", line 342, in <lambda>
    lambda x: edge_model_fn()(x), name="edge_model")  # pylint: disable=unnecessary-lambda
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\sequential.py", line 103, in _build
    net = layer(*net)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\nets\mlp.py", line 143, in _build
    self._input_shape = tuple(inputs.get_shape().as_list())
AttributeError: 'NoneType' object has no attribute 'get_shape'

originally defined at:
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 39, in make_mlp_model
    snt.nets.MLP([LATENT_SIZE] * NUM_LAYERS, activate_final=True),
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\nets\mlp.py", line 81, in __init__
    super(MLP, self).__init__(custom_getter=custom_getter, name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]


originally defined at:
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 40, in make_mlp_model
    snt.LayerNorm()
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\sequential.py", line 65, in __init__
    super(Sequential, self).__init__(name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]


originally defined at:
  File "C:/Users/Farshid/PycharmProjects/clique/Main2.py", line 110, in <module>
    model = models.EncodeProcessDecode(edge_output_size=2, node_output_size=2)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 101, in __init__
    self._encoder = MLPGraphIndependent()
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 53, in __init__
    global_model_fn=make_mlp_model)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\modules.py", line 342, in __init__
    lambda x: edge_model_fn()(x), name="edge_model")  # pylint: disable=unnecessary-lambda
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 710, in __init__
    super(Module, self).__init__(custom_getter=custom_getter, name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]


originally defined at:
  File "C:/Users/Farshid/PycharmProjects/clique/Main2.py", line 110, in <module>
    model = models.EncodeProcessDecode(edge_output_size=2, node_output_size=2)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 101, in __init__
    self._encoder = MLPGraphIndependent()
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 53, in __init__
    global_model_fn=make_mlp_model)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\modules.py", line 332, in __init__
    super(GraphIndependent, self).__init__(name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]


originally defined at:
  File "C:/Users/Farshid/PycharmProjects/clique/Main2.py", line 110, in <module>
    model = models.EncodeProcessDecode(edge_output_size=2, node_output_size=2)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 101, in __init__
    self._encoder = MLPGraphIndependent()
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 48, in __init__
    super(MLPGraphIndependent, self).__init__(name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]


originally defined at:
  File "C:/Users/Farshid/PycharmProjects/clique/Main2.py", line 110, in <module>
    model = models.EncodeProcessDecode(edge_output_size=2, node_output_size=2)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\demos\models.py", line 100, in __init__
    super(EncodeProcessDecode, self).__init__(name=name)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\sonnet\python\modules\base.py", line 215, in __init__
    custom_getter_=self._custom_getter)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 154, in make_template
    **kwargs)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 224, in make_template_internal
    create_graph_function=create_graph_function_)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 281, in __init__
    self._stacktrace = traceback.format_stack()[:-2]
```

**Comment by vbapst** [comment]
Hi Farshid, 

you cannot use a `GraphIndependent` module if your input graph has not node states. Either provide dummy features, or do the initial encoding of your graph yourself.

**Comment by FarshidShekari** [comment]
thank you.
