### ISSUE TITLE
error in "networkx_to_data_dict" method

### ISSUE THREAD

**Issue by FarshidShekari** [deepmind/graph_nets#34]
Why below error raise:
```
Traceback (most recent call last):
  File "C:/Users/Farshid/PycharmProjects/CommunityDetection/Main.py", line 104, in <module>
    num_nodes_min_max_tr, theta)
  File "C:\Users\Farshid\PycharmProjects\CommunityDetection\Helper.py", line 234, in create_placeholders
    input_graphs, force_dynamic_num_graphs=True)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\utils_tf.py", line 327, in placeholders_from_networkxs
    data_type_hint.as_numpy_dtype())
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\utils_np.py", line 337, in networkxs_to_graphs_tuple
    edge_shape_hint, data_type_hint)
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\utils_np.py", line 200, in networkx_to_data_dict
    for x in edge_attr_dicts
  File "C:\Users\Farshid\AppData\Local\Programs\Python\Python35\lib\site-packages\graph_nets\utils_np.py", line 201, in <listcomp>
    if x[GRAPH_NX_FEATURES_KEY] is not None
KeyError: 'features'
```

**Comment by vbapst** [comment]
The edges in your networkx graph instance must have a "features" attribute.
Use:
```
your_graph_nx.add_edge(node_1, node_2, features=None)
```
when adding an edge.

We may want to relax this assumption in the future, though.

**Comment by FarshidShekari** [comment]
I copied shortest path example but I don't know why it don't work? this is my `add_shortst_path` function code:
```
 for node_index, node_feature in graph.nodes(data=True):
        input_graph.add_node(node_index, features=create_feature(node_feature, input_node_fields))
        target_node = to_one_hot(create_feature(node_feature, target_node_fields).astype(int), 2)[0]
        target_graph.add_node(node_index, features=target_node)
        comId = int(node_feature["ComId"])
        solution_length = max([solution_length, comId])

    for receiver, sender, features in graph.edges(data=True):
        input_graph.add_edge(sender, receiver, features=create_feature(features, input_edge_fields))
        target_edge = to_one_hot(create_feature(features, target_edge_fields).astype(int), 2)[0]
        target_graph.add_edge(sender, receiver, features=target_edge)

    input_graph.graph["features"] = np.array([0.0])
    target_graph.graph["features"] = np.array([solution_length], dtype=float)
```
