### ISSUE TITLE
Error in multi feature using for target nodes 

### ISSUE THREAD

**Issue by FarshidShekari** [deepmind/graph_nets#37]
I want to add multiple features to target nodes like below in shortest path example:
```
    input_node_fields = ("solution", "ComId")
    input_edge_fields = ("solution", "ComId")
    target_node_fields = ("solution", "ComId")
    target_edge_fields = ("solution",)
```
when I want to run my code, rise below  error:

```
Traceback (most recent call last):
  File "C:/Users/Farshid/PycharmProjects/CommunityDetection/Main.py", line 104, in <module>
    num_nodes_min_max_tr, theta)
  File "C:\Users\Farshid\PycharmProjects\CommunityDetection\Helper.py", line 234, in create_placeholders
    rand, batch_size, num_nodes_min_max, theta)
  File "C:\Users\Farshid\PycharmProjects\CommunityDetection\Helper.py", line 209, in generate_networkx_graphs
    input_graph, target_graph = graph_to_input_target(graph)
  File "C:\Users\Farshid\PycharmProjects\CommunityDetection\Helper.py", line 168, in graph_to_input_target
    target_node = to_one_hot(create_feature(node_feature, target_node_fields).astype(int), 2)[0]
  File "C:\Users\Farshid\PycharmProjects\CommunityDetection\Helper.py", line 28, in to_one_hot
    one_hot = np.eye(max_value)[indices]
IndexError: index 2 is out of bounds for axis 0 with size 2
```
Can someone help me?
@mateuszmalinowski
@pbattaglia

**Comment by alvarosg** [comment]
(Closing due to inactivity)
