### ISSUE TITLE
install issue, gpu ,tensorflow1.12

### ISSUE THREAD

**Issue by 2877992943** [deepmind/graph_nets#40]
GPU install tensorflow 1.12, following the instruction on README:

"pip install graph_nets tensorflow_gpu tensorflow_probability_gpu"

find below error, 

Traceback (most recent call last):
  File "Node_Apply_GCN_symptom_deepmind.py", line 1, in <module>
    import sonnet as snt
  File "/usr/local/lib/python2.7/dist-packages/sonnet/__init__.py", line 39, in <module>
    from sonnet.python import custom_getters
  File "/usr/local/lib/python2.7/dist-packages/sonnet/python/custom_getters/__init__.py", line 21, in <module>
    from sonnet.python.custom_getters import bayes_by_backprop
  File "/usr/local/lib/python2.7/dist-packages/sonnet/python/custom_getters/bayes_by_backprop.py", line 97, in <module>
    _OK_PZATION_TYPE = tf.contrib.distributions.FULLY_REPARAMETERIZED
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 48, in <module>
    from tensorflow.contrib import distribute
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/__init__.py", line 34, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 71, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/__init__.py", line 25, in <module>
    import tensorflow.python.estimator.estimator_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator_lib.py", line 42, in <module>
    from tensorflow.python.estimator.keras import model_to_estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/keras.py", line 27, in <module>
    from tensorflow.python.estimator import estimator as estimator_lib
ImportError: cannot import name estimator

**Comment by 2877992943** [comment]
docker run --name graph --runtime=nvidia -it rxthinking:tfp_graphnet /bin/bash -c "python"

if run import sonnet as snt .  in interactive python shell,no error reported
