### ISSUE TITLE
execute jupyter notebook

### ISSUE THREAD

**Issue by ytgcljj** [deepmind/graph_nets#5]
Hello, I execute jupyter notebook. I can't see anything on the page.

**Comment by alvarosg** [comment]
Could you describe the steps you follow to execute the demo in the jupyter notebook?

Are you able to see the demos in the colaboratory links provided?

[Run "shortest path demo" in browser](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/shortest_path.ipynb)
[Run "sort demo" in browser](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/sort.ipynb)
[Run "physics demo" in browser](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/physics.ipynb)

**Comment by ytgcljj** [comment]
test@test:~/graph_nets/graph_nets$ jupyter notebook --ip=192.168.6.113
[I 16:29:14.313 NotebookApp] Serving notebooks from local directory: /home/test/graph_nets/graph_nets
[I 16:29:14.313 NotebookApp] The Jupyter Notebook is running at:
[I 16:29:14.314 NotebookApp] http://192.168.6.113:8888/?token=3720036fe1897ce51b7658d9e0aaecbaf802337285d631b8
[I 16:29:14.314 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:29:14.314 NotebookApp] No web browser found: could not locate runnable browser.
[C 16:29:14.314 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://192.168.6.113:8888/?token=3720036fe1897ce51b7658d9e0aaecbaf802337285d631b8
[W 16:29:15.317 NotebookApp] 404 GET /api/kernels/0b3af765-af29-4ee0-9d67-4d036a95de45/channels?session_id=543d4d7175554cdb8898f264cfb4cd50 (192.168.6.4): Kernel does not exist: 0b3af765-af29-4ee0-9d67-4d036a95de45
[W 16:29:15.381 NotebookApp] 404 GET /api/kernels/0b3af765-af29-4ee0-9d67-4d036a95de45/channels?session_id=543d4d7175554cdb8898f264cfb4cd50 (192.168.6.4) 96.71ms referer=None
[W 16:29:19.394 NotebookApp] Replacing stale connection: 0b3af765-af29-4ee0-9d67-4d036a95de45:543d4d7175554cdb8898f264cfb4cd50
[W 16:29:25.463 NotebookApp] Notebook demos/sort.ipynb is not trusted
[I 16:29:26.273 NotebookApp] Kernel started: 34b4ed89-21d5-445e-a727-580a066a28c0
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 259, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 267, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[I 16:29:29.271 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 259, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 267, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[I 16:29:32.278 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 259, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 267, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[I 16:29:35.288 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 259, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 267, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[I 16:29:38.300 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 259, in init_sockets
    self.init_iopub(context)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 267, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/iostream.py", line 66, in __init__
    self.io_loop = IOLoop(make_current=False)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/util.py", line 208, in __new__
    instance.initialize(**args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
TypeError: initialize() got an unexpected keyword argument 'make_current'
[W 16:29:41.314 NotebookApp] KernelRestarter: restart failed
[W 16:29:41.314 NotebookApp] Kernel 34b4ed89-21d5-445e-a727-580a066a28c0 died, removing from map.
[W 16:30:26.457 NotebookApp] Timeout waiting for kernel_info reply from 34b4ed89-21d5-445e-a727-580a066a28c0
[E 16:30:26.458 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 34b4ed89-21d5-44
![0000](https://user-images.githubusercontent.com/27713475/47347665-4dbd3a80-d6e2-11e8-9de6-0476b1d96830.png)

**Comment by Frostinassiky** [comment]
Do you install jupyter correctly? It looks like a mismatched tornado version. 

Look here
https://github.com/jupyter/help/issues/272#issue-285474280

**Comment by alvarosg** [comment]
Closing due to inactivity.
