### ISSUE TITLE
Placeholders from data dicts with no edges

### ISSUE THREAD

**Issue by Ung0d** [deepmind/graph_nets#80]
Hi,
I am currently trying out graph_nets and came across a problem, that I wasn't able to solve.

My graphs have node and global properties as well as senders/receivers, but use no edge properties at all. I tried to create a placeholder from such a data dict and provide it as input for my model, however, session.run calls involving this placeholder yield the following error.

```
Traceback (most recent call last):
  File "graphNN.py", line 312, in <module>
    graphs_tuple_np = sess.run(graphs_tuple_ph, feed_dict)
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/felix/python/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 258, in for_fetch
    type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>
```

Minimal code, that reproduces my error:

```
n_node = 3
senders = [0, 1, 2]  # Indices of nodes sending the edges
receivers = [1, 2, 0]  # Indices of nodes receiving the edges

data_dict = {
    "n_node": n_node,
    "senders": senders,
    "receivers": receivers,
}

tf.reset_default_graph()

graphs_tuple_ph = utils_tf.placeholders_from_data_dicts([data_dict])

with tf.Session() as sess:
  feed_dict = utils_tf.get_feed_dict(graphs_tuple_ph, utils_np.data_dicts_to_graphs_tuple([data_dict]))
  graphs_tuple_np = sess.run(graphs_tuple_ph, feed_dict)
```

Why is this not working?

**Comment by alvarosg** [comment]
You should use the `utils_tf.make_runnable_in_session` [method](https://github.com/deepmind/graph_nets/blob/6f33ee4244ebe016b4d6296dd3eb99625fd9f3af/graph_nets/utils_tf.py#L488). Long story short, `sess.run` calls do not accept None's, so they need to be replaced by `tf.no_op()'s`, so when they go through the session they become None.

You should only use that "runnable" graph for that, for anything else, keep using the `graphs_tuple_ph` with the correct None's.

```
tf.reset_default_graph()

graphs_tuple_ph = utils_tf.placeholders_from_data_dicts([data_dict])

graphs_tuple_ph_runnable = utils_tf.make_runnable_in_session(graphs_tuple_ph)
with tf.Session() as sess:
  feed_dict = utils_tf.get_feed_dict(graphs_tuple_ph, utils_np.data_dicts_to_graphs_tuple([data_dict]))
  graphs_tuple_np = sess.run(graphs_tuple_ph_runnable, feed_dict)

```

**Comment by Ung0d** [comment]
Ah I see. Thanks.
